spring:
<<<<<<< HEAD

  main.allow-bean-definition-overriding: true

=======
>>>>>>> b1687a5115efb64f7dd4429ae73580c998edcd85
  output.ansi.enabled: ALWAYS

  datasource:
    url: "jdbc:mysql://localhost:3306/todo_list_spring?serverTimezone=GMT"
    username: sylene
    password: my-db64B

  jpa:
    show-sql: true

    hibernate.ddl-auto: update

